### ISSUE TITLE
`_staticWithdrawMorpho` can underflow

### ISSUE THREAD

**Issue by julien-devatom** [morpho-org/metamorpho#273] opened 2023-10-26 07:55 UTC
https://github.com/morpho-org/metamorpho/blob/dce999e9a0d7cecf77cd56533bbeb60e7b9dcffe/src/MetaMorpho.sol#L560

The argument of the function is the number of assets of the user (when called in maxWithdraw).
The objective of this function is to truncate the amount that cannot be withdrawn due to a lack of liquidity. However, the substraction is done globally while we are comparing a user balance. Let's take an example.
Let's say Alice has 10 USDC to withdraw, and the vault has 2 markets in the withdraw queue: 
- market A with 5 usdc withdrawable
- market B with 10 usdc withdrawable
the idle amount is 0.

So first, remaining is 10. 

- When passing in the first market, remaining = 10 - 5 = 5. 
- When passing in second market, remaining = 5 - 10 => Underflow.

## Fixes:

use `zeroFloorSub` when substracting withdrawable amount.

NB: the `_withdrawMorpho` function is not impacted due to [this line](https://github.com/morpho-org/metamorpho/blob/dce999e9a0d7cecf77cd56533bbeb60e7b9dcffe/src/MetaMorpho.sol#L739)

**Comment by Rubilmax** [comment] 2023-10-26 10:03
duplicate of #203?

**Comment by Rubilmax** [comment] 2023-10-26 10:04
I confirm it's a duplicate of #203 and the code referenced is outdated
See the `main` branch

**Closed by Rubilmax** 2023-10-26 10:04 UTC
